<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>c++ try_catch throw « NotBeCN</title>
  <meta name="description" content="             使用throw抛出异常     本人节选自《21天学通C++》一书 &nbsp;&nbsp;&nbsp; 抛出异常（也称为抛弃异常）即检测是否产生异常，在C++中，其采用throw语句来实现，如果检测到产生异常，则抛出异常。该语句的格式为： throw 表达式; &nbsp;&nbsp;...">

  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="https://notbe.cn/2017/10/12/weixin_34409741_90135236.html">
  <link rel="alternate" type="application/rss+xml" title="NotBeCN" href="https://notbe.cn/feed.xml" />
</head>


  <body>

    <div class="header-placeholder"></div>
<header class="header">
  <div class="wrapper">
    <div id="sidebar-toggle">TOC</div>
    <a class="site-title" href="/">NotBeCN</a>
    <nav class="site-nav">
      
        
        <a class="page-link" href="/about/" target="_blank">关于</a>
      
        
        <a class="page-link" href="https://uzshare.com" target="_blank">社区</a>
      
        
        <a class="page-link" href="/donate/" target="_blank">Donate</a>
      
        
        <a class="page-link" href="/games/shejiyazi/" target="_blank">射个鸭子</a>
      
    </nav>
  </div>
</header>


    <div class="page-content">
      <div class="wrapper">
        <div class="col-main">
          <div class="post">

  <header class="post-header">
    <h1 class="post-title">c++ try_catch throw</h1>
    <p class="post-meta">Oct 12, 2017</p>
  </header>

  <article class="post-content">
    <div id="article_content" class="article_content clearfix csdn-tracking-statistics" data-pid="blog" data-mod="popu_307" data-dsm="post"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <link rel="stylesheet" href="https://csdnimg.cn/release/phoenix/template/css/ck_htmledit_views-f57960eb32.css"> 
 <div class="htmledit_views" id="content_views"> 
  <div class="content-detail markdown-body"> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">使用throw抛出异常</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;"><br> 本人节选自《21天学通C++》一书<br> &nbsp;&nbsp;&nbsp; 抛出异常（也称为抛弃异常）即检测是否产生异常，在C++中，其采用throw语句来实现，如果检测到产生异常，则抛出异常。该语句的格式为：<br> throw 表达式;<br> &nbsp;&nbsp;&nbsp; 如果在try语句块的程序段中（包括在其中调用的函数）发现了异常，且抛弃了该异常，则这个异常就可以被try语句块后的某个catch语句所捕获并处理，捕获和处理的条件是被抛弃的异常的类型与catch语句的异常类型相匹配。由于C++使用数据类型来区分不同的异常，因此在判断异常时，throw语句中的表达式的值就没有实际意义，而表达式的类型就特别重要。<br> 【范例20-2】处理除数为0的异常。该范例将上述除数为0的异常可以用try/catch语句来捕获异常，并使用throw语句来抛出异常，从而实现异常处理，实现代码如代码清单20-2所示。<br> 代码清单20-2<br> 1&nbsp;&nbsp;&nbsp; #include&lt;iostream.h&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //包含头文件<br> 2&nbsp;&nbsp;&nbsp; #include&lt;stdlib.h&gt;<br> 3&nbsp;&nbsp;&nbsp; double fuc(double x, double y)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //定义函数<br> 4&nbsp;&nbsp;&nbsp; {<br> 5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if(y==0)<br> 6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br> 7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; throw y;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //除数为0，抛出异常<br> 8&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br> 9&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; return x/y;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //否则返回两个数的商<br> 10&nbsp;&nbsp;&nbsp; }<br> 11&nbsp;&nbsp;&nbsp; void main()<br> 12&nbsp;&nbsp;&nbsp; {<br> 13&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; double res;<br> 14&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; try&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //定义异常<br> 15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br> 16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; res=fuc(2,3);<br> 17&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cout&lt;&lt;"The result of x/y is : "&lt;&lt;res&lt;&lt;endl;<br> 18&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; res=fuc(4,0);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //出现异常<br> 19&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br> 20&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; catch(double)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //捕获并处理异常<br> 21&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<br> 22&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cerr&lt;&lt;"error of dividing zero.\n";<br> 23&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; exit(1);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //异常退出程序<br> 24&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<br> 25&nbsp;&nbsp;&nbsp; }<br> 【运行结果】在Visual C++中新建一个【C++ Source File】文件，输入上述的代码，编译无误后运行。<br> 【范例解析】上述代码中，在主函数main()的第14～19行中使用了try语句定义异常，其中包含3条有可能出现异常的语句，它们为调用两个数相除的函数。在代码的第20～24行定义了异常处理，即捕获异常后执行该段代码中的语句。此外，在函数fuc()的代码5～8行通过throw语句抛出异常。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">注意：一般来说，throw语句通常与try- catch或try-finally语句一起使用，可以使用throw语句显式引发异常。<br> ////////////</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">c++ try_catch<br> &nbsp;<br> 1、基础介绍<br> try<br> {<br> //程序中抛出异常<br> throw value;<br> }<br> catch(valuetype v)<br> {<br> //例外处理程序段<br> }<br> 语法小结：throw抛出值，catch接受，当然，throw必须在“try语句块”中才有效。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">2、深入throw：<br> (i)、程序接受到throw语句后就会自动调用析构器，把该域（try后的括号内）对象clean up，然后再进<br> 入catch语句（如果在循环体中就退出循环）。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">这种机制会引起一些致命的错误，比如，当“类”有指针成员变量时（又是指针！），在 “类的构建器<br> ”中的throw语句引起的退出，会导致这个指针所指向的对象没有被析构。这里很基础，就不深入了，提<br> 示一下，把指针改为类就行了，比如模板类来代替指针，在模板类的内部设置一个析构函数。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">(ii)、<strong>语句“throw;”抛出一个无法被捕获的异常，即使是catch(...)也不能捕捉到，这时进入终止函数</strong><br><strong>，见下catch。</strong></p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">3、深入catch：<br> 一般的catch出现的形式是：<br> try{}<br> catch(except1&amp;){}<br> catch(except2&amp;){}<br> catch(...){} //接受所有异常<br> 一般都写成引用（except1&amp;），原因很简单，效率。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">问题a：抛出异常，但是catch不到异常怎么办？（<strong>注意没有java类似的finally语句</strong>）<br> 在catch没有捕获到匹配的异常的时候，会调用默认的终止函数。可以调用set_terminate()来设置终止函数，参数是一个函数指针，类型是：void (*terminate)()。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">到这里，可以题个问题：“没有try-catch,直接在程序中"throw;"，会怎么样？”</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;"><br> 其他一些技巧：<br> 4、try一个函数体，形式如下<br> void fun(type1,type2) try－－－－try放在函数体后<br> {<br> &nbsp;&nbsp; 函数定义<br> }<br> catch(typeX){}<br> 这个用法的效果就相当于:<br> void fun()&nbsp;<br> {<br> &nbsp;&nbsp; try{函数定义}<br> }</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;"><br> 5、throw一个函数体，形式如下：<br> void fun (); // 能抛出任何类型的异常<br> void fun () throw(except1,except2,except3)&nbsp;<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // 后面括号里面是一个异常参数表，本例中只能抛出这3中异常<br> void fun () throw()&nbsp;&nbsp; // 参数表为空，不能抛出异常</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">问题b：假设fun()中抛出了一个不在“异常参数表”中的异常，会怎么样？</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">答：调用set_terminate()中设定的终止函数。然而，这只是表面现象，实际上是调用默认的unexpected()函数，然而这个默认的unexpected()调用了set_terminate()中设定的终止函数。可以用set_unexpected()来设置unexpected,就像set_terminate()一样的用法，但是在设定了新的“unexpected()”之后，就不会再调用set_terminater中设定的终止函数了。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;">这个语法是很有用的，因为在用别人的代码时，不知道哪个地方会调用什么函数又会抛出什么异常，用一个异常参数表在申明时限制一下，很实用。</p> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;"><br></p> 
   <p><font><span style="font-size:14px;">本文转自茄子_2008博客园博客，原文链接：http://www.cnblogs.com/xd502djj/archive/2010/09/28/1837396.html</span></font><span style="font-size:14px;font-family:verdana, Arial, Helvetica, sans-serif;">，如需转载请自行联系原作者。</span></p> 
   <div>
    <br>
   </div> 
   <p style="font-family:verdana, Arial, Helvetica, sans-serif;font-size:14px;"><br></p> 
  </div> 
 </div> 
</div>
  </article>
  
  




</div>

        </div>
        <div class="col-second">
          <div class="col-box col-box-author">
  <img class="avatar" src="https://uzstatic-360cdn.belost.xyz/theme/default/images/logo.png" alt="柚子社区">
  <div class="col-box-title name">NotBeCN</div>
  <!-- <p>最新资讯</p> -->
  <p class="contact">
    
    <a href="mailto:fandyvon@163.com" target="_blank">邮箱</a>
    
    <a href="https://uzshare.com" target="_blank">柚子社区</a>
    
    <a href="https://uzzz.org" target="_blank">找组织</a>
    
  </p>
</div>

<div class="col-box">
  <div class="col-box-title">最新</div>
  <ul class="post-list">
    
      <li><a class="post-link" href="/2019/05/14/zxh1220_90138586.html">[原创软件] [软件发布] 定时备份文件发送邮箱，不再怕数据丢失了</a></li>
    
      <li><a class="post-link" href="/2019/05/14/weixin_45037290_90140056.html">Get智能写作满月记 ——产品篇</a></li>
    
      <li><a class="post-link" href="/2019/05/14/nulio__90138386.html">《深度探索C++对象模型》..............</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_41248707_90140031.html">mysql 多表联查之连接查询</a></li>
    
      <li><a class="post-link" href="/2019/05/13/qq_21122683_90125902.html">golang基础(二)</a></li>
    
      <li><a class="post-link" href="/2019/05/13/1557726108256.html">今日份的PTA刷题</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90137366.html">Android之折线图</a></li>
    
      <li><a class="post-link" href="/2019/05/12/zzzfffei_90136638.html">Android之实现选中时改变样式</a></li>
    
  </ul>
</div>

<div class="col-box post-toc hide">
  <div class="col-box-title">目录</div>
</div>

<div class="col-box">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- right_sidebar -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8889449066804352"
       data-ad-slot="2081363239"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


        </div>
      </div>
    </div>

    <footer class="footer">
<div class="wrapper">
&copy; 2019 
</div>
</footer>

<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]}});</script>
<script src="/js/easybook.js"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123344652-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123344652-5');
</script>


<script data-ad-client="ca-pub-8889449066804352" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.async = true;
  hm.src = "https://hm.baidu.com/hm.js?9b378145d7399199b371d067f4c8be96";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>




  </body>

</html>
